sudo: false
language: node_js
node_js:
  - "5"
cache:
  directories:
    - node_modules
matrix:
  include:
    - env: UNDERSCORE=1.4.4 BACKBONE=1.0
    - env: UNDERSCORE=1.5 BACKBONE=1.0
    - env: UNDERSCORE=1.7 BACKBONE=1.1
    - env: UNDERSCORE=1.7 BACKBONE=1.0
    - env: UNDERSCORE=1.6 BACKBONE=1.0
    - env: UNDERSCORE=1.4.4 BACKBONE=1.1.0
    - env: UNDERSCORE=1.5 BACKBONE=1.1
    - env: LODASH=2.4 BACKBONE=1.1
    # - env: LODASH=3.0 BACKBONE=1.1
    # - env: LODASH=3.1 BACKBONE=1.0
    # - env: LODASH=3.10 BACKBONE=1.2
    # - env: LODASH=4 BACKBONE=1.2
install:
  - ./ci.sh
after_success:
  - npm run-script coverage
